name: Windows Github Action CI

on:
  pull_request:
    branches:
      - SYCLomatic

env:
  BUILD_CONCURRENCY: 2
  MACOS_BUILD_CONCURRENCY: 3
  TEST_TIMEOUT: 3600

jobs:
  windows-build-lit:
    name: windows-build-lit
    runs-on: win_build_sc
    outputs:
      build_success: ${{ steps.Echo-Build-Success.outputs.build_success }}
    strategy:
      fail-fast: false

    steps:

      - name: Cleanup Workspace
        run: |
          if exist c2s.obj rd /s /q c2s.obj
          if exist c2s.src/build rd /s /q c2s.src/build
        shell: cmd





      
