name: Windows Github Action CI

on:
  pull_request:
    branches:
      - SYCLomatic

env:
  BUILD_CONCURRENCY: 2
  MACOS_BUILD_CONCURRENCY: 3
  TEST_TIMEOUT: 3600

jobs:
  windows-build-lit:
    name: windows-build-lit
    runs-on: win_build_sc
    outputs:
      build_success: ${{ steps.Echo-Build-Success.outputs.build_success }}
    strategy:
      fail-fast: false

        steps:
      - uses: actions/checkout@v2
        with:
          path: c2s.src
      - name: Checkout Test Repo
        #uses: actions/checkout@v2
        #with:
        #  repository: 
        #  path: test_repo
        run: |
          if exist test_repo rd /s /q test_repo
          mkdir test_repo
          mkdir c2s.obj
          mkdir c2s.src
        shell: cmd 

      - name: Cleanup Workspace
        run: |
          if exist c2s.obj rd /s /q c2s.obj
          if exist c2s.src/build rd /s /q c2s.src/build
        shell: cmd

      - name: Process ENV
        id: process_env
        run: |
          for mask_value in $(C:/jq-win64.exe -r ".[]" $GITHUB_WORKSPACE/../../../mask_env_values.json); do 
              echo "add mask for $mask_value"; 
              echo "::add-mask::$mask_value"; 
          done
        shell: bash

      - name: Prepare Env
        uses: ./c2s.src/devops/actions/prepare_env_win



      
