name: Windows Github Action CI

on:
  pull_request:
    branches:
      - SYCLomatic

env:
  BUILD_CONCURRENCY: 2
  MACOS_BUILD_CONCURRENCY: 3
  TEST_TIMEOUT: 3600

jobs:
  windows-build-lit:
    name: windows-build-lit
    runs-on: win_build_sc
    outputs:
      build_success: ${{ steps.Echo-Build-Success.outputs.build_success }}
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
        with:
          path: c2s.src
      - name: Process ENV
        id: process_env
        run: |
          for mask_value in $(C:/jq-win64.exe -r ".[]" $GITHUB_WORKSPACE/../../../mask_env_values.json); do 
              echo "add mask for $mask_value"; 
              echo "::add-mask::$mask_value"; 
          done
        shell: bash

      - name: Prepare Env
        uses: ./c2s.src/devops/actions/prepare_env_win
      - id: Echo-Build-Success
        run: echo "::set-output name=build_success::true"

      - name: Set_CUDA_Env8.0
        if: |
          always() &&
          steps.Echo-Build-Success.outputs.build_success == 'true'
        run: |
          echo "CUDA_PATH=$CUDAROOT/v8.0" >> $GITHUB_ENV
        shell: bash

      - name: Lit_CUDA8.0
        if: |
          always() &&
          steps.Echo-Build-Success.outputs.build_success == 'true'
        run: |
          Remove-Item -Recurse -Force -Path c2s.src/clang
          Remove-Item -Recurse -Force -Path c2s.src/lld
        shell: bash

      
